default: &default
  adapter: sqlite3
  timeout: 5000

development: 
  <<: *default # same as the deafult above.
  database: db/todos-dev.sqlite3

production: 
  <<: *default
  database: db/todos-prod.sqlite3

